replicaCount: 1

image:
  repository: wernight/dante
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 1080
  nodePort: 30080

config:
  sockdConfig: |
    logoutput: stderr
    internal: 0.0.0.0 port = 1080
    external: eth0
    method: none
    user.privileged: root
    user.notprivileged: nobody
    client pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
    }
    # Atlas CIDR
    pass {
        from: 0.0.0.0/0 to: 10.66.224.0/21
    }
    block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
    }

