apiVersion: apps/v1
kind: Deployment
metadata:
  name: dante-socks5
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dante-socks5
  template:
    metadata:
      labels:
        app: dante-socks5
    spec:
      containers:
      - name: dante
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/sockd.conf
          subPath: sockd.conf
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
      volumes:
      - name: config-volume
        configMap:
          name: dante-config

