apiVersion: v1
kind: Service
metadata:
  name: dante-socks5-service
spec:
  selector:
    app: dante-socks5
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

